digest_key: "CustomServerDigest"
listen_addr: "127.0.0.1"
listen_port: 10060
external_url: "http://localhost:10060"
base_path: "/lbp"
db_conn: "postgres://postgres@localhost/sacklite"
redis_conn: "127.0.0.1:6379"
log_level: "info"

server_desc: "best server ever"
banner_image_url: null

eula: |
  some legalese or something idk
announcement: |
  hello :)
  wow, so multi-line :O

resource_dir: "./resrc"
resource_size_limit: 2000000 # 2 MB
slot_limit: 20

create_user_on_connect: true
rename_users_automatically: true

verify_client_digest: true
verify_npticket_signature: true
verify_npticket_expiry: true
