ALTER TABLE users
    ALTER COLUMN icon SET NOT NULL,
    ALTER COLUMN icon SET DEFAULT '',
    ALTER COLUMN lbp2_planets SET NOT NULL,
    ALTER COLUMN lbp2_planets SET DEFAULT '',
    ALTER COLUMN lbp3_planets SET NOT NULL,
    ALTER COLUMN lbp3_planets SET DEFAULT '',
    ALTER COLUMN cross_control_planet SET NOT NULL,
    ALTER COLUMN cross_control_planet SET DEFAULT '',
    ALTER COLUMN yay2 SET NOT NULL,
    ALTER COLUMN yay2 SET DEFAULT '',
    ALTER COLUMN meh2 SET NOT NULL,
    ALTER COLUMN meh2 SET DEFAULT '',
    ALTER COLUMN boo2 SET NOT NULL,
    ALTER COLUMN boo2 SET DEFAULT '';

ALTER TABLE slots
    ALTER COLUMN icon SET NOT NULL,
    ALTER COLUMN icon SET DEFAULT '';