ALTER TABLE users
    ALTER COLUMN icon DROP NOT NULL,
    ALTER COLUMN icon DROP DEFAULT,
    ALTER COLUMN lbp2_planets DROP NOT NULL,
    ALTER COLUMN lbp2_planets DROP DEFAULT,
    ALTER COLUMN lbp3_planets DROP NOT NULL,
    ALTER COLUMN lbp3_planets DROP DEFAULT,
    ALTER COLUMN cross_control_planet DROP NOT NULL,
    ALTER COLUMN cross_control_planet DROP DEFAULT,
    ALTER COLUMN yay2 DROP NOT NULL,
    ALTER COLUMN yay2 DROP DEFAULT,
    ALTER COLUMN meh2 DROP NOT NULL,
    ALTER COLUMN meh2 DROP DEFAULT,
    ALTER COLUMN boo2 DROP NOT NULL,
    ALTER COLUMN boo2 DROP DEFAULT;

ALTER TABLE slots
    ALTER COLUMN icon DROP NOT NULL,
    ALTER COLUMN icon DROP DEFAULT;